@ECHO OFF&&SETLOCAL ENABLEDELAYEDEXPANSION&&TITLE  Download from github.com/joshuacline&&COLOR 0E
:HEXPROMPT
CLS&&ECHO ====================================================================&&ECHO                     Josh's ASCII-2-Hex Parser&&ECHO ====================================================================
IF DEFINED HEX_ACCUMULATOR ECHO HEX OUTPUT=[%HEX_ACCUMULATOR%]
ECHO TYPE ASCII INPUT
SET HEX_INPUT=&&SET /P "HEX_INPUT=$>>"
SET "HEX_OUTPUT=HEX_ACCUMULATOR"
CALL:HEX_INPUT
GOTO:HEXPROMPT
:HEX_INPUT
IF NOT DEFINED HEX_INPUT EXIT /B
FOR /F "delims=" %%G in ('CMD.EXE /D /U /C ECHO %HEX_INPUT%^| FIND /V ""') do (CALL SET "HEX_IN=%%G"&&CALL:HEX_OUTPUT)
CALL SET "%HEX_OUTPUT%=%HEX_ACCUM%"&&SET HEX_ACCUM=&&SET HEX_OUTPUT=&&SET HEX_INPUT=
EXIT /B
:HEX_OUTPUT
IF "%HEX_IN%"==" " SET HEXED=1&&CALL SET HEX_OUT=20
::IF "%HEX_IN%"=="^!" SET HEXED=1&&CALL SET HEX_OUT=21
IF "%HEX_IN%"=="#" SET HEXED=1&&CALL SET HEX_OUT=23
IF "%HEX_IN%"=="$" SET HEXED=1&&CALL SET HEX_OUT=24
IF "%HEX_IN%"=="%" SET HEXED=1&&CALL SET HEX_OUT=25
::IF "%HEX_IN%"=="^&" SET HEXED=1&&CALL SET HEX_OUT=26
IF "%HEX_IN%"=="(" SET HEXED=1&&CALL SET HEX_OUT=28
IF "%HEX_IN%"==")" SET HEXED=1&&CALL SET HEX_OUT=29
IF "%HEX_IN%"=="*" SET HEXED=1&&CALL SET HEX_OUT=2a
IF "%HEX_IN%"=="+" SET HEXED=1&&CALL SET HEX_OUT=2b
IF "%HEX_IN%"=="," SET HEXED=1&&CALL SET HEX_OUT=2c
IF "%HEX_IN%"=="-" SET HEXED=1&&CALL SET HEX_OUT=2d
IF "%HEX_IN%"=="." SET HEXED=1&&CALL SET HEX_OUT=2e
IF "%HEX_IN%"=="/" SET HEXED=1&&CALL SET HEX_OUT=2f
IF "%HEX_IN%"=="0" SET HEXED=1&&CALL SET HEX_OUT=30
IF "%HEX_IN%"=="1" SET HEXED=1&&CALL SET HEX_OUT=31
IF "%HEX_IN%"=="2" SET HEXED=1&&CALL SET HEX_OUT=32
IF "%HEX_IN%"=="3" SET HEXED=1&&CALL SET HEX_OUT=33
IF "%HEX_IN%"=="4" SET HEXED=1&&CALL SET HEX_OUT=34
IF "%HEX_IN%"=="5" SET HEXED=1&&CALL SET HEX_OUT=35
IF "%HEX_IN%"=="6" SET HEXED=1&&CALL SET HEX_OUT=36
IF "%HEX_IN%"=="7" SET HEXED=1&&CALL SET HEX_OUT=37
IF "%HEX_IN%"=="8" SET HEXED=1&&CALL SET HEX_OUT=38
IF "%HEX_IN%"=="9" SET HEXED=1&&CALL SET HEX_OUT=39
IF "%HEX_IN%"==":" SET HEXED=1&&CALL SET HEX_OUT=3a
IF "%HEX_IN%"==";" SET HEXED=1&&CALL SET HEX_OUT=3b
IF "%HEX_IN%"=="=" SET HEXED=1&&CALL SET HEX_OUT=3d
IF "%HEX_IN%"=="?" SET HEXED=1&&CALL SET HEX_OUT=3f
IF "%HEX_IN%"=="@" SET HEXED=1&&CALL SET HEX_OUT=40
IF "%HEX_IN%"=="A" SET HEXED=1&&CALL SET HEX_OUT=41
IF "%HEX_IN%"=="B" SET HEXED=1&&CALL SET HEX_OUT=42
IF "%HEX_IN%"=="C" SET HEXED=1&&CALL SET HEX_OUT=43
IF "%HEX_IN%"=="D" SET HEXED=1&&CALL SET HEX_OUT=44
IF "%HEX_IN%"=="E" SET HEXED=1&&CALL SET HEX_OUT=45
IF "%HEX_IN%"=="F" SET HEXED=1&&CALL SET HEX_OUT=46
IF "%HEX_IN%"=="G" SET HEXED=1&&CALL SET HEX_OUT=47
IF "%HEX_IN%"=="H" SET HEXED=1&&CALL SET HEX_OUT=48
IF "%HEX_IN%"=="I" SET HEXED=1&&CALL SET HEX_OUT=49
IF "%HEX_IN%"=="J" SET HEXED=1&&CALL SET HEX_OUT=4a
IF "%HEX_IN%"=="K" SET HEXED=1&&CALL SET HEX_OUT=4b
IF "%HEX_IN%"=="L" SET HEXED=1&&CALL SET HEX_OUT=4c
IF "%HEX_IN%"=="M" SET HEXED=1&&CALL SET HEX_OUT=4d
IF "%HEX_IN%"=="N" SET HEXED=1&&CALL SET HEX_OUT=4e
IF "%HEX_IN%"=="O" SET HEXED=1&&CALL SET HEX_OUT=4f
IF "%HEX_IN%"=="P" SET HEXED=1&&CALL SET HEX_OUT=50
IF "%HEX_IN%"=="Q" SET HEXED=1&&CALL SET HEX_OUT=51
IF "%HEX_IN%"=="R" SET HEXED=1&&CALL SET HEX_OUT=52
IF "%HEX_IN%"=="S" SET HEXED=1&&CALL SET HEX_OUT=53
IF "%HEX_IN%"=="T" SET HEXED=1&&CALL SET HEX_OUT=54
IF "%HEX_IN%"=="U" SET HEXED=1&&CALL SET HEX_OUT=55
IF "%HEX_IN%"=="V" SET HEXED=1&&CALL SET HEX_OUT=56
IF "%HEX_IN%"=="W" SET HEXED=1&&CALL SET HEX_OUT=57
IF "%HEX_IN%"=="X" SET HEXED=1&&CALL SET HEX_OUT=58
IF "%HEX_IN%"=="Y" SET HEXED=1&&CALL SET HEX_OUT=59
IF "%HEX_IN%"=="Z" SET HEXED=1&&CALL SET HEX_OUT=5a
IF "%HEX_IN%"=="[" SET HEXED=1&&CALL SET HEX_OUT=5b
IF "%HEX_IN%"=="\" SET HEXED=1&&CALL SET HEX_OUT=5c
IF "%HEX_IN%"=="]" SET HEXED=1&&CALL SET HEX_OUT=5d
IF "%HEX_IN%"=="_" SET HEXED=1&&CALL SET HEX_OUT=5f
IF "%HEX_IN%"=="a" SET HEXED=1&&CALL SET HEX_OUT=61
IF "%HEX_IN%"=="b" SET HEXED=1&&CALL SET HEX_OUT=62
IF "%HEX_IN%"=="c" SET HEXED=1&&CALL SET HEX_OUT=63
IF "%HEX_IN%"=="d" SET HEXED=1&&CALL SET HEX_OUT=64
IF "%HEX_IN%"=="e" SET HEXED=1&&CALL SET HEX_OUT=65
IF "%HEX_IN%"=="f" SET HEXED=1&&CALL SET HEX_OUT=66
IF "%HEX_IN%"=="g" SET HEXED=1&&CALL SET HEX_OUT=67
IF "%HEX_IN%"=="h" SET HEXED=1&&CALL SET HEX_OUT=68
IF "%HEX_IN%"=="i" SET HEXED=1&&CALL SET HEX_OUT=69
IF "%HEX_IN%"=="j" SET HEXED=1&&CALL SET HEX_OUT=6a
IF "%HEX_IN%"=="k" SET HEXED=1&&CALL SET HEX_OUT=6b
IF "%HEX_IN%"=="l" SET HEXED=1&&CALL SET HEX_OUT=6c
IF "%HEX_IN%"=="m" SET HEXED=1&&CALL SET HEX_OUT=6d
IF "%HEX_IN%"=="n" SET HEXED=1&&CALL SET HEX_OUT=6e
IF "%HEX_IN%"=="o" SET HEXED=1&&CALL SET HEX_OUT=6f
IF "%HEX_IN%"=="p" SET HEXED=1&&CALL SET HEX_OUT=70
IF "%HEX_IN%"=="q" SET HEXED=1&&CALL SET HEX_OUT=71
IF "%HEX_IN%"=="r" SET HEXED=1&&CALL SET HEX_OUT=72
IF "%HEX_IN%"=="s" SET HEXED=1&&CALL SET HEX_OUT=73
IF "%HEX_IN%"=="t" SET HEXED=1&&CALL SET HEX_OUT=74
IF "%HEX_IN%"=="u" SET HEXED=1&&CALL SET HEX_OUT=75
IF "%HEX_IN%"=="v" SET HEXED=1&&CALL SET HEX_OUT=76
IF "%HEX_IN%"=="w" SET HEXED=1&&CALL SET HEX_OUT=77
IF "%HEX_IN%"=="x" SET HEXED=1&&CALL SET HEX_OUT=78
IF "%HEX_IN%"=="y" SET HEXED=1&&CALL SET HEX_OUT=79
IF "%HEX_IN%"=="z" SET HEXED=1&&CALL SET HEX_OUT=7a
IF "%HEX_IN%"=="{" SET HEXED=1&&CALL SET HEX_OUT=7b
IF "%HEX_IN%"=="}" SET HEXED=1&&CALL SET HEX_OUT=7d
IF "%HEX_IN%"=="~" SET HEXED=1&&CALL SET HEX_OUT=7e
IF "%HEXED%"=="1" CALL SET "HEX_OUT=%HEX_OUT%00"
IF "%HEXED%"=="1" CALL SET "HEX_ACCUM=%HEX_ACCUM%%HEX_OUT%"
SET HEX_IN=&&SET HEXED=&&SET HEX_OUT=
EXIT /B
